name: LewisCommands
version: ${project.version}
main: me.lewismercer.lewiscommands.LewisCommands
api-version: 1.17
authors: [ Lewismercer ]
description: Basic commands for the SMP server
commands:
  map:
    description: Shows the map!
  balance:
    description: Check you're balance!
    aliases: bal
  balancetop:
    description: Shows the top players!
    aliases: baltop
  addbalance:
    description: Add to a players balance!
    aliases: addbal
  takebalance:
    description: Takes balance away from a player!
    aliases: takebal
  setbalance:
    description: Set a players balance!
    aliases: setbal
  pay:
    description: Pay another player!
  sell:
    description: Use this to sell a netherite ingot!
  setrank:
    description: Set a players rank!
  tell:
    description: Simple tell msg
    aliases:
      - t
      - msg
      - w
  reply:
    description: Send a reply
    aliases:
      - r
  mute:
    description: Mute a pleb
  nickname:
    description: Set a nick
    aliases:
      - nick
  store:
    description: Open the store
    aliases:
      - buy
      - shop