name: LewisCommands
version: ${project.version}
main: me.lewismercer.lewiscommands.LewisCommands
api-version: 1.16
authors: [ Lewismercer ]
description: Basic commands for the SMP server
commands:
  streamers:
    description: Shows the streamers on the SMP!
  map:
    description: Shows the map!
  sumo:
    description: Teleport to the sumo platform, prepare to die!
  balance:
    description: Check you're balance!
    aliases: bal
  balancetop:
    description: Shows the top players!
    aliases: baltop
  addbalance:
    description: Add to a players balance!
    aliases: addbal
  takebalance:
    description: Takes balance away from a player!
    aliases: takebal
  setbalance:
    description: Set a players balance!
    aliases: setbal
  pay:
    description: Pay another player!
  sell:
    description: Use this to sell a netherite ingot!
