name: WorldwideSMP
version: ${project.version}
main: com.worldwidesmp.worldwidesmp.WorldwideSMP
api-version: 1.16
load: STARTUP
authors: [ TheDreps, TheRdMelon ]
description: Plugin to run on Worldwide SMP
website: worldwidesmp.com
